version: '3.8'

services:
  nginx:
    image: nginx:1.24-alpine
    ports:
      - '80:80'
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    build:
      dockerfile: docker/php-fpm/Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
